spring.application.name=loanManagement
spring.datasource.url=jdbc:postgresql://localhost:5432/northerarc
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=MySecretKeyForJwtTokenGenerationThatIsLongEnough123456
jwt.expiration=86400000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


app.seed.enabled=true
